#!/usr/bin/env bash
# Embed the canonical shared references into every skill's references/ folder.
#
# Skills must be independently executable (no cross-skill path assumptions),
# so each skill carries its own copy of the shared contracts. shared/*.md is
# the single source of truth; the copies under skills/*/references/ are
# generated by this script and must not be edited by hand.
#
# Idempotent: safe to re-run any number of times. Skill-specific reference
# files (anything not named like a shared doc) are left untouched.
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED_DIR="$PLUGIN_ROOT/shared"
SKILLS_DIR="$PLUGIN_ROOT/skills"

if [ ! -d "$SHARED_DIR" ] || [ ! -d "$SKILLS_DIR" ]; then
  echo "error: expected $SHARED_DIR and $SKILLS_DIR to exist" >&2
  exit 1
fi

shared_docs=("$SHARED_DIR"/*.md)
if [ ${#shared_docs[@]} -eq 0 ]; then
  echo "error: no shared docs found in $SHARED_DIR" >&2
  exit 1
fi

copied=0
for skill_dir in "$SKILLS_DIR"/*/; do
  skill_name="$(basename "$skill_dir")"
  refs_dir="${skill_dir}references"
  mkdir -p "$refs_dir"
  for doc in "${shared_docs[@]}"; do
    cp "$doc" "$refs_dir/$(basename "$doc")"
    copied=$((copied + 1))
  done
  echo "embedded ${#shared_docs[@]} shared reference(s) into skills/$skill_name/references/"
done

echo "done: $copied file copies across $(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ') skill(s)"
